name: Build and Release Inline HTML

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build with inline HTML
        run: npm run build:inline

      - name: Rename and prepare index.html
        run: |
          mkdir artifact
          cp dist/index.html artifact/index.html

      - name: Create GitHub Release with index.html
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: artifact/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
